#ifndef _ELF_FAVOR_H
#define _ELF_FAVOR_H

#include "elf/reloc-macros.h"

START_RELOC_NUMBERS (elf_favor_reloc_type)
  RELOC_NUMBER (R_FAVOR_NONE, 0)
  RELOC_NUMBER (R_FAVOR_J22_PCREL, 1)
  RELOC_NUMBER(R_FAVOR_IMM16_PCREL, 2)
  RELOC_NUMBER(R_FAVOR_IMM32_PCREL, 3)
  RELOC_NUMBER(R_FAVOR_IMM48_PCREL, 4)
  RELOC_NUMBER(R_FAVOR_IMM64_PCREL, 5)
  RELOC_NUMBER(R_FAVOR_BIT32_LI_PCREL, 6)
END_RELOC_NUMBERS (R_FAVOR_max)

#endif